server:
  port: 8082

logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081
    #      addresses= http://vpn.kidoneself.com:8081
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:


spring:
  datasource:
    url: jdbc:mysql://vpn.kidoneself.com:3306/jd-xxljob?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jd@xxljob
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xxl.job.executor.po
