version: '3'

services:
  pyja:
    restart: always
    build: # 构建自定义镜像
      context: .      # 指定dockerfile文件的所在路径
      dockerfile: Dockerfile   # 指定Dockerfile文件名称
    container_name: pj  #指定容器名
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Shanghai
#    links:
#      - jd_mysql


#  mysql:
#    image: mysql:5.7
#    container_name: xxl_job
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: xxl-job
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456
#      MYSQL_ROOT_PASSWORD: 123456
##    volumes:
##      - ./data/databases_root/demo_db:/var/lib/mysql
##      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    command: [
#        '--character-set-server=utf8',
#        '--collation-server=utf8_general_ci',
#        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
#    ]
