version: '3'

services:
  pyja:
    restart: always
    build: # 构建自定义镜像
      context: .      # 指定dockerfile文件的所在路径
      dockerfile: Dockerfile   # 指定Dockerfile文件名称
    image: ${IMAGE_NAME}:${ALPINE_VERSION}   #指定镜像名和版本
    container_name: ${CONTAINER_NAME}  #指定容器名
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:

      - "${HOST_ADDRESS1}:3306"
      - "${HOST_ADDRESS2}:8081"
